typography_spectrum: 0.9308119448833168
color:
  brandStrength: 0.45228242594748735
  lightness: 0.6933388086035848
  saturation: 0.8437220377381891
  rhythmicContrast: 0.45300886896438897
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.3750992885325104
author:
  name: Michael Grassman
  email: mgrassman@designing-solutions.com
  url: designing-solutions.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dcde5ab9-37bd-4b1e-880b-4b9401dcdf14.png
name: Designing Solutions WD
navigation:
  - name: What We Do
    id: c37f6a7d-e5cd-4a0a-99b8-9ccbdeefc3d5
    type: content
title: designing solutions
description: so you don't have to
